### ISSUE TITLE
Use $http with $fh.getCloudParams

### ISSUE THREAD

**Issue by evanshortiss** [feedhenry-staff/ngFeedHenry#3]
This might be of use, although it would cause us to lose some potential updates if more FH SDK logic is placed in this module. Basically, maybe we remove $fh.cloud and replace it with $http and inject the SDK params for $fh.getCloudParams

**Comment by bleathem** [comment]
Advantages I can think of:
- a more familiar naming convention for angular developers
- better integration with the Angular digest lifecycle
